export const genres = [
  { value: '', label: 'Seleccionar un género' },
  { value: "hardcover-fiction", label: "Ficción de Tapa Dura" },
  { value: "hardcover-nonfiction", label: "No Ficción de Tapa Dura" },
  { value: "paperback-fiction", label: "Ficción de Bolsillo" },
  { value: "paperback-nonfiction", label: "No Ficción de Bolsillo" },
  { value: "advice-how-to-and-miscellaneous", label: "Consejos y Autoayuda" },
  { value: "e-book-fiction", label: "Libros Electrónicos de Ficción" },
  { value: "e-book-nonfiction", label: "Libros Electrónicos de No Ficción" },
  { value: "combined-print-and-e-book-fiction", label: "Ficción Combinada (Impreso y Electrónico)" },
  { value: "combined-print-and-e-book-nonfiction", label: "No Ficción Combinada (Impreso y Electrónico)" },
  { value: "picture-books", label: "Libros Infantiles Ilustrados" },
  { value: "chapter-books", label: "Libros Infantiles de Capítulos" },
  { value: "series-books", label: "Libros Infantiles de Serie" },
  { value: "young-adult-hardcover", label: "Juvenil de Tapa Dura" },
  { value: "science", label: "Ciencia" },
  { value: "sports", label: "Deportes" },
  { value: "travel", label: "Viajes" },
  { value: "business-books", label: "Negocios" },
  { value: "graphic-books-and-manga", label: "Ficción Gráfica y Manga" },
  { value: "health", label: "Salud" },
  { value: "education", label: "Educación" },
  { value: "religion-spirituality-and-faith", label: "Religión y Espiritualidad" }
]